# Generated by Django 2.1.1 on 2018-09-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180930_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagspost',
            name='tag_post',
        ),
    ]
