# Generated by Django 2.1.1 on 2018-09-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_tagspost_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagspost',
            name='tag_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
