# Generated by Django 2.1.1 on 2018-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tagspost_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagspost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
