# Generated by Django 2.1.1 on 2018-09-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tagspost_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagspost',
            name='tag_post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
