# Generated by Django 2.1.1 on 2018-09-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180929_2210'),
        ('order', '0002_auto_20180926_1640'),
    ]

    operations = [
    ]
