# Generated by Django 2.1.1 on 2018-10-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
    ]
