# Generated by Django 2.1.1 on 2018-10-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_productinbasket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
