# Generated by Django 2.1.1 on 2018-10-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181002_2325'),
        ('order', '0008_auto_20181004_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductImage'),
        ),
    ]
