# Generated by Django 2.1.1 on 2018-10-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20181009_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.CharField(blank=True, default=123, max_length=300),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='img',
            field=models.CharField(blank=True, default=123, max_length=300),
        ),
    ]
