# Generated by Django 2.1.1 on 2018-10-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20181009_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='img',
        ),
    ]
