# Generated by Django 2.1.1 on 2018-10-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20181009_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
