# Generated by Django 2.1.1 on 2018-09-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180929_1818'),
        ('products', '0003_auto_20180930_0000'),
    ]

    operations = [
    ]
