# Generated by Django 2.1.1 on 2018-09-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20180930_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='name_color',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
