# Generated by Django 2.1.1 on 2018-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='importance',
            field=models.CharField(choices=[('pr', 'Paramount'), ('se', 'Secondary')], default='se', max_length=2),
        ),
    ]
